name: "Run Tests"

on:
  push:
    branches: 
      - master
      - beta
  pull_request:
    branches: 
      - master
      - beta

jobs:
  build:
    name: Run Tests Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}